Porting //eve/staging/2019-ETTIN->//eve/development/MAINLINE at head (1515830) - using branchspec //eve/staging/2019-ETTIN->//eve/development/MAINLINE
========================================

Change 1515157 by baldur@eve_mainline_BALDUR-WS on 2019/05/28 15:09:01

[eve 2019-ETTIN][audio] 2019-05-28 13:51:32.

Sound for Additional Animation State for the World Ark Ship

https://jira.ccpgames.com/browse/GFX-5525

========================================

Change 1515166 by joshb@eve_branches_staging_2019-ETTIN_joshb-pc on 2019/05/28 15:13:44

More Triglavian Invasion NPC loot table tweaks

https://jira.ccpgames.com/browse/TEH-1375

========================================

Change 1515175 by hjaltil@eve_branches_staging_2019-ETTIN_hjaltil-pc on 2019/05/28 15:22:40

Very high CPU usage on Cluster Singleton Node - GetCombatAnomalyInstances https://jira.ccpgames.com/browse/TQ-131984

* Removed ReconstructContentPieces function, this was allowing each dungeon based content provider to refresh its data from the server even when the data wasn't needed.
* Now only invalidating the dungeon instances/content pieces instead of directly reconstructing everything, opting rather to construct the content pieces selectively upon SystemScanDone, Signal/Anomaly tracker updates, OnNewState and SessionChanged

========================================

Change 1515195 by freyr@eve_branches_staging_2019-ETTIN_freyr-pc on 2019/05/28 15:37:49

Agency3.0: Pirate Stronghold entries are not removed from the Agency upon completion
https://jira.ccpgames.com/browse/EVEDEV-7196

Clearing the content data from cache when the content is unregistered.  This removes the FOB registration as soon as it is killed as the tale ends and the agency registry cleanup is run.

========================================

Change 1515202 by freyr@eve_branches_staging_2019-ETTIN_freyr-pc on 2019/05/28 15:42:12

Invasion NPCs have very short lock times
https://jira.ccpgames.com/browse/TQ-131990

Exposing reaction delay milliseconds parameter for activating parameters to the base Combat For Entity behavior tree.  That way we can easily add randomized reaction delay for behaviors.

========================================

Change 1515208 by olafurth@eve_branches_staging_2019-ETTIN_olafurth-ws on 2019/05/28 15:47:02

Adding a check for shieldEllipsoid to the HasImpactConfigurationShield function in evespaceobject2

https://jira.ccpgames.com/browse/TQ-131979

========================================

Change 1515210 by joshb@eve_branches_staging_2019-ETTIN_joshb-pc on 2019/05/28 15:48:35

Clarifying the warning message when leaving or kicking someone from a corporation that is at war

https://jira.ccpgames.com/browse/TQ-131919

========================================

Change 1515221 by joshb@eve_branches_staging_2019-ETTIN_joshb-pc on 2019/05/28 15:57:05

Updating the start of war mail text to clarify that the attackers are the ones who need to pay the bills.

https://jira.ccpgames.com/browse/TQ-131966

========================================

Change 1515242 by hrafng@eve_branches_staging_2019-ETTIN_hrafn-ws on 2019/05/28 16:08:08

Prevent irrelevant stages of the Triglavian Invasion from being displayed in the Agency. https://jira.ccpgames.com/browse/TQ-131992

========================================

Change 1515262 by hjaltil@eve_branches_staging_2019-ETTIN_hjaltil-pc on 2019/05/28 16:15:04

Agency3: Fix sentry error spam for NoneType content cards.

https://sentry.io/organizations/ccpgames/issues/1020749979

========================================

Change 1515307 by hjaltil@eve_branches_staging_2019-ETTIN_hjaltil-pc on 2019/05/28 16:37:54

AttributeError: 'NoneType' object has no attribute 'GetPirateStrongholds' https://jira.ccpgames.com/browse/TQ-131995

* Now checking if content provider is available before attempting access.

========================================

Change 1515370 by hrafng@eve_branches_staging_2019-ETTIN_hrafn-ws on 2019/05/28 17:01:17

New feature notify window shows up in character creation https://jira.ccpgames.com/browse/TQ-131997

========================================

Change 1515371 by arnarb@eve_branches_staging_2019-ETTIN_arnarb-ws on 2019/05/28 17:01:29

Very high CPU usage on Cluster Singleton Node - GetCombatAnomalyInstances
https://jira.ccpgames.com/browse/TQ-131984

- Now using KeyVal instead of DungeonInfo instances for cached dungeon data in an attempt to reduce marshalling time
- Removed unused method from dungeonInstanceCacheMgr

========================================

Change 1515402 by hjaltil@eve_branches_staging_2019-ETTIN_hjaltil-pc on 2019/05/28 17:22:26

Probe Scanner Window not showing when probe map set to fullscreen. https://jira.ccpgames.com/browse/TQ-131985

* No longer overriding the open function causing some weird behaviour

========================================

Change 1515464 by arnarb@eve_branches_staging_2019-ETTIN_arnarb-ws on 2019/05/28 17:48:41

Very high CPU usage on Cluster Singleton Node - GetCombatAnomalyInstances
https://jira.ccpgames.com/browse/TQ-131984

- Now instead of constructing a list of [None, None ..., None] when players should just see the number, we just hand the client the an integer which the client will then unpack to the list of Nones
- Now filtering out all systems beyond known space for the method above 
- According to my testing, this reduces the amount of data sent over the wire by around 75% (the filtering by kspace) and the time each call takes (according to timeit) by around 75% as well

========================================

Change 1515492 by einarth@eve_branches_staging_2019-ETTIN_einarth-pc on 2019/05/28 18:06:25

DB usage of user.Users_SelectForCharSelect5 is way too high
https://jira.ccpgames.com/browse/TQ-131983

Few things changed here:

* The @organizations table variable got a new field, 'warableID' which is set to the corporationID of the character, unless that corporation is a part of an alliance, in which case we set it to the allianceID (lines 51-54 in the proc).  Logic being that corporations can't be at war on their own when in an alliance.  This cuts down the number of joins and checks we need to perform as we can now just join on the warableID instead of checking both corp and alliance.

* We now gather up all the wars involving the warableID in a CTE, where we _only_ look at the ownerIDs in question and pay no attention to any timestamps and furthermore, do the war.wars lookup with two queries UNION'd together instead of one with an OR-clause in the JOIN. Somewhat surprisingly, this is significantly faster.

* The last step now is to filter OwnerWars on timestamps and UNION with ally wars.

querying for user 12415031 (the user owning the CEO character of the executor corp of the 2nd highest alliance in terms of historic war involvement) on TQTEST yielded the following results:

Users_SelectForCharSelect4:                     CPU time = 16 ms,  elapsed time = 19 ms.
Users_SelectForCharSelect5:                     CPU time = 437 ms,  elapsed time = 425 ms.
Users_SelectForCharSelect_fixcandidate   CPU time = 125 ms,  elapsed time = 124 ms.

EBS 8131

========================================

Change 1515504 by hjaltil@eve_branches_staging_2019-ETTIN_hjaltil-pc on 2019/05/28 18:15:39

Agency3: Introduce throttling and telemetry to DungeonInstanceCacheMgr functions that have to do with getting dungeon instances

* Safeguards against spammers trying to overload the cluster
* Allows us to get more data on the function calls of DungeonInstanceCacheMgr

========================================

Change 1515547 by marshall@marshall_MARSHALL-WS_4433 on 2019/05/29 03:40:23

Last batch of ETTIN zh translation

========================================

Change 1515716 by marshall@marshall_MARSHALL-WS_4433 on 2019/05/29 10:59:26

Create June Daily Login Campaign for Serenity and additional translation fixes.

========================================

Change 1515779 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/05/29 11:53:12

Republishing TFU Telegraphing VFX for radius fix.  Republishing Mothership and controller for Animation State tweak https://jira.ccpgames.com/browse/GFX-5527 https://jira.ccpgames.com/browse/GFX-5515

========================================

Change 1515830 by baldur@eve_mainline_BALDUR-WS on 2019/05/29 12:32:03

[eve 2019-ETTIN][audio] 2019-05-29 12:24:18.


Sound update for fortfication bubble graphics

https://jira.ccpgames.com/browse/GFX-5527

[git-p4: depot-paths = "//eve/branches/development/MAINLINE/carbon/src/Trinity/": change = 1515876]