Porting //eve/staging/2019-INCUBUS->//eve/development/MAINLINE at head (1575229) - using branchspec //eve/staging/2019-INCUBUS->//eve/development/MAINLINE
========================================

Change 1573768 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/09/24 13:57:24

Removing moon file as it was renamed https://jira.ccpgames.com/browse/TC-44

========================================

Change 1573784 by hjaltil@eve_branches_staging_2019-INCUBUS_hjaltil-pc on 2019/09/24 14:22:56

Fixing fallout from CL 1572719

* DarkStyleButtonPrimary and DarkStyleIconButton now use the new default_underlay_mouse_*_color attributes.

========================================

Change 1573818 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/09/24 14:30:26

First Playable UI reward window
https://jira.ccpgames.com/browse/TFO-3201

 - fixing the browsing a bit (browsing still hidden though)

========================================

Change 1573832 by einarth@eve_branches_staging_2019-INCUBUS_einarth-pc on 2019/09/24 14:48:26

Protect against direct trade scams by double confirmation
https://jira.ccpgames.com/browse/TFO-3219

Restore old code until we can polish

========================================

Change 1573866 by tyrfingur@eve_branches_staging_2019-INCUBUS_tyrfingur-ws on 2019/09/24 15:09:02

Abyssal Trace appearing but does not have any graphics
https://jira.ccpgames.com/browse/EVEDEV-8380

- AbyssalTrace spaceobject controller variable was not being initialized correctly.
- Added wait time to remove graphical pop

========================================

Change 1573878 by eve_automation@TC_p4_EC2_Windows_i_069f8007628528207_1c8c3d988af95287_31795a49edfc6b92 on 2019/09/24 15:14:42

[eve 2019-INCUBUS] Automatic VCXPROJ submission from 15

This might create build loops, but it was deemed valuable enough to be able to sync these.
https://teamcity.evetech.net/viewLog.html?buildId=7399946
!nobuild

Source Changes
----------------
[Eve Engine] 1573738 by eric (Eric  Nielsen)
[eve 2019-INCUBUS][audio] Fix build errors.
----------------
[Eve Engine] 1573666 by eric (Eric  Nielsen)
[eve 2019-INCUBUS][audio] Add ability to send controller variables to Wwise as an RTPC from a controller.
https://jira.ccpgames.com/browse/TC-10
https://jira.ccpgames.com/browse/TC-80
----------------

========================================

Change 1573891 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/09/24 15:31:42

First Playable UI reward window
https://jira.ccpgames.com/browse/TFO-3201

 - breaking the code into more files and preparing to add the evergreen stuff

========================================

Change 1573924 by baldur@eve_mainline_BALDUR-WS on 2019/09/24 15:45:57

https://jira.ccpgames.com/browse/TC-45

warp prep sound edits

========================================

Change 1573948 by arnarb@eve_branches_staging_2019-INCUBUS on 2019/09/24 15:57:26

Wallet tooltip displays incorrect balance after gaining/losing money
https://jira.ccpgames.com/browse/EVEDEV-8441

- Now sending out the old balance as first argument of the event as it was before

========================================

Change 1574000 by einarth@eve_branches_staging_2019-INCUBUS_einarth-pc on 2019/09/24 16:15:45

Clicking orbit in the selected item window will always orbit at 500m
https://jira.ccpgames.com/browse/EVEDEV-8416
&
Exceptions at using selected items window for launched drones
https://jira.ccpgames.com/browse/EVEDEV-8432

Bypass MergeMenus for when getting a single item menu from these contexts.

========================================

Change 1574004 by baldur@eve_mainline_BALDUR-WS on 2019/09/24 16:16:17

Audio atmo for Stellar Observatory

https://jira.ccpgames.com/browse/GFX-5863

========================================

Change 1574006 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/09/24 16:17:26

Republishing TriGlavian Observatory wreck for texture files update https://jira.ccpgames.com/browse/TC-110

========================================

Change 1574029 by einarth@eve_branches_staging_2019-INCUBUS_einarth-pc on 2019/09/24 16:24:34

cluError: structureDeployment.py(180) RenameStructure - addressCache.py(107) setcomp - unhashable type: 'set'
https://jira.ccpgames.com/browse/EVEDEV-8442

Fix a set comprehension which was wrong.

========================================

Change 1574042 by einarth@eve_branches_staging_2019-INCUBUS_einarth-pc on 2019/09/24 16:32:50

cluError: marketRegion.py(1698) CancelOrdersInStructure - AttributeError: batchOrderCancelationSize
https://jira.ccpgames.com/browse/EVEDEV-8431

Fixed a type-o.

========================================

Change 1574089 by ganjie@eve_branches_staging_2019-INCUBUS_ganjie-pc on 2019/09/24 17:08:56

Created license for Minmatar Snowline Bladeracer SKINs  https://jira.ccpgames.com/browse/TM-387

========================================

Change 1574180 by hjaltil@eve_branches_staging_2019-INCUBUS_hjaltil-pc on 2019/09/24 18:01:23

As a developer, I have removed the "Show Aura" link in the operations info panel. https://jira.ccpgames.com/browse/PSYCHO-2102

========================================

Change 1574199 by eve_automation@TC_p4_EC2_Windows_i_0c4eca7db724c0ed4_78f38dad93c1c633_6a55b794e8af04fe on 2019/09/24 18:09:11

[eve 2019-INCUBUS] Automatic skin icon submission from 1574089.6

https://teamcity.evetech.net/viewLog.html?buildId=7405561
!nobuild

Source Changes
----------------
[Eve Engine] 1574089 by ganjie (Jie Gan)
Created license for Minmatar Snowline Bladeracer SKINs  https://jira.ccpgames.com/browse/TM-387
----------------

========================================

Change 1574307 by danielp@eve_branches_staging_2019-INCUBUS_danielp-pc on 2019/09/24 19:22:23

UI polish - reverse order of expiry settings
https://jira.ccpgames.com/browse/TFO-3105

Reverse the order of the expiry settings in the bookmark location window to make more sense. The options are still not final, so this will pretty sure change again somehow.

========================================

Change 1574464 by danielp@eve_branches_staging_2019-INCUBUS_danielp-pc on 2019/09/25 10:08:34

Update bookmark visibility on sensor overlay
https://jira.ccpgames.com/browse/TFO-3075

* Add the visibility button also to folders (and not only to subfolders)
* Save the settings as tuples (folderID, subfolderID) instead of only the subfolderID.
** Use yaml.safe_dump to save those to DB

========================================

Change 1574504 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/09/25 10:25:00

Implement: Integrated Seasonal Campaign UI for Rookie DLI
https://jira.ccpgames.com/browse/TFO-3287

 - starting on the evergreen in the window, adding huge tabs in the window

========================================

Change 1574539 by einarth@eve_branches_staging_2019-INCUBUS_einarth-pc on 2019/09/25 10:47:54

Radial menu fails to appear with exception
https://jira.ccpgames.com/browse/EVEDEV-8448

trivial mistake from yesterday corrected.

========================================

Change 1574545 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/09/25 10:50:45

First Playable UI reward window
https://jira.ccpgames.com/browse/TFO-3201

 - adding a ui pointer to the redeeming queue when something is claimed

========================================

Change 1574584 by linzi@linzi_linzi-lap_2101 on 2019/09/25 11:10:28

https://jira.ccpgames.com/browse/EVEDEV-8443

========================================

Change 1574606 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/09/25 11:15:15

First Playable UI reward window
https://jira.ccpgames.com/browse/TFO-3201

 - adding the temporary text to the text file
 - adding the help icons

========================================

Change 1574620 by einarth@eve_branches_staging_2019-INCUBUS_einarth-pc on 2019/09/25 11:19:21

Unable to set destination / waypoint to solar system bookmark
https://jira.ccpgames.com/browse/EVEDEV-8429

Seeing as GetMapIDs() is searching for a station, structure or a solarsystem, it seems kind of silly that it doesn't check if the input is a solarsystem before searching up the hierarchy.... Henceforth, let's do that.

========================================

Change 1574739 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/09/25 12:07:12

Buy remotely warning claims item will be deposited in currently docked station
https://jira.ccpgames.com/browse/EVEDEV-8452

 - fixing it so we use the correct stationID when displaying the warning

========================================

Change 1574742 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/09/25 12:10:09

Add filter for the shortcts in the ESC Window
https://jira.ccpgames.com/browse/TFO-3236

 - adding the tab name to the tooltip entries if the list is being filtered

========================================

Change 1574774 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/09/25 12:44:42

Copying Help Pointers into chat turns text between links into part of the link
https://jira.ccpgames.com/browse/EVEDEV-8453

 - changing it so it does ignore the '/a' tag (which closes the link) if there are help pointer links that are ignored

========================================

Change 1574814 by eric@eric_MAINLINE_FOR_REAL on 2019/09/25 13:16:09

[eve 2019-INCUBUS][audio] Fix error where audio was breaking the warp preparation bar when audio was disabled.
https://jira.ccpgames.com/browse/EVEDEV-8427

========================================

Change 1574842 by hjaltil@eve_branches_staging_2019-INCUBUS_hjaltil-pc on 2019/09/25 13:39:24

As a player, I know how to display Aura again after I've minimized her conversation window. https://jira.ccpgames.com/browse/PSYCHO-2093

* OperationsSvc now places a highlight on the aura window button in the neocom once the player minimizes the aura conversation window.
* This highlight fades out in 5 seconds

========================================

Change 1574853 by freyr@eve_branches_staging_2019-INCUBUS_freyr-pc on 2019/09/25 13:47:08

R-Click Compare option fails for certain ships
https://jira.ccpgames.com/browse/EVEDEV-8440

changed get_meta_group_name and get_meta_group_description to check for None groups first and return an empty stiring if None.

========================================

Change 1574865 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/09/25 13:51:18

First Playable UI reward window
https://jira.ccpgames.com/browse/TFO-3201

 - adding the new reward window to the character selectin screen
 - it only pops up if there is something that can be claimed (this needs to adjusted to also take seasons into account)
 - the window is modal when it's in character selection

========================================

Change 1574880 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/09/25 14:01:40

First Playable UI reward window
https://jira.ccpgames.com/browse/TFO-3201

 - fixing an issue where it would not scroll to the next reward after claiming

========================================

Change 1574930 by einarth@eve_branches_staging_2019-INCUBUS_einarth-pc on 2019/09/25 14:22:49

Add macho service routing based on userID to allow User Nodes
https://jira.ccpgames.com/browse/TFO-3282

Created serviceID 53 "user" with mod 32.

CORE 1094

========================================

Change 1575037 by audunn@eve_branches_staging_2019-INCUBUS_audunn-ws on 2019/09/25 15:30:46

Triglavian Ores cannot be searched or easily found in Market
https://jira.ccpgames.com/browse/TQ-132700

- Left over market groups for triglavian ore moved to FSD including their localization data

========================================

Change 1575074 by baldur@eve_mainline_BALDUR-WS on 2019/09/25 15:57:54

https://jira.ccpgames.com/browse/TC-12

audio edits for stellar observatory

========================================

Change 1575143 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/09/25 16:18:02

Republishing Golem, Nyx and halloween_19_minmatar faction for 2019 aAlloween SKIN fix 
https://jira.ccpgames.com/browse/EVEDEV-8438 https://jira.ccpgames.com/browse/EVEDEV-8437 
https://jira.ccpgames.com/browse/EVEDEV-8428

========================================

Change 1575153 by dylan@eve_branches_staging_2019-INCUBUS_dylan-ws on 2019/09/25 16:25:24

20129 Triglavian October - Stellar Fleet Dungeon - BALANCE

- Removed the laboratory (but not the dungeon) from the vanguard and assault roaming fleets. This should result in them not landing in the dungeon, but they should still hit the dungeon lobby.

https://jira.ccpgames.com/browse/TEH-1719

========================================

Change 1575189 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/09/25 16:32:11

Publishing Bloodraider factrion for the 2019-Halloween SKIN https://jira.ccpgames.com/browse/ENYA-202

========================================

Change 1575229 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/09/25 16:42:29

Creatig materialSet ID 2516 for Bloodraider hulls, 2019 Halloween SKIN https://jira.ccpgames.com/browse/ENYA-8

[git-p4: depot-paths = "//eve/branches/development/MAINLINE/carbon/src/Trinity/": change = 1575751]